#!/bin/bash

ORIGINAL_FONT="Lat15-Terminus16"
TARGET_FONT="Lat15-Terminus28x14"

dmesg -n 3

echo 2 > /sys/class/graphics/fbcon/rotate_all

setfont "$TARGET_FONT"

sleep 5

/opt/tdlas/dashboard

setfont "$ORIGINAL_FONT"

clear

exit 0
